### ISSUE TITLE
Any plan to add more options ?

### ISSUE THREAD

**Issue by rohitsangwan01** [patricknicolosi/whatsapp_sender#1]
Also , can you use Streams instead of valueNotifiers 
it will be much easier to use with streams

**Comment by patricknicolosi** [comment]
I will evaluate the use of Streams. I wanted to implement sending images and files when I have some time.

**Comment by rohitsangwan01** [comment]
well i wrote almost whole library ( for sending Messages only ) , and then i found this one 😅

**Comment by rohitsangwan01** [comment]
@patricknicolosi my repo for reference 
https://github.com/rohitsangwan01/whatsapp_bot_flutter
